### ISSUE TITLE
unable to sails lift after installing sails globally

### ISSUE THREAD

**Issue by shaunstanislaus** [balderdashy/sails#3252] opened 2015-09-23 01:54 UTC
```bash
shaunstanislaus@Master ~/workspace $ sails new testProject
info: Created a new Sails app `testProject`!
shaunstanislaus@Master ~/workspace $ cd tes
testProject/  test_example/ testgitflow/
shaunstanislaus@Master ~/workspace $ cd test
-bash: cd: test: No such file or directory
shaunstanislaus@Master ~/workspace $ cd tes
testProject/  test_example/ testgitflow/
shaunstanislaus@Master ~/workspace $ cd testProject/
shaunstanislaus@Master ~/workspace/testProject $ ls
Gruntfile.js  README.md     api/          app.js        assets/       config/       node_modules/ package.json  tasks/        views/
shaunstanislaus@Master ~/workspace/testProject $ sails lift

info: Starting app...

module.js:338
    throw err;
    ^

Error: Cannot find module 'express/node_modules/connect'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/sails/lib/hooks/session/index.js:25:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/sails/lib/app/configuration/index.js:63:34
    at /usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:3741:15
    at forOwn (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:2106:15)
    at Function.reduce (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:3738:9)
    at Configuration.defaultConfig (/usr/local/lib/node_modules/sails/lib/app/configuration/index.js:58:18)
shaunstanislaus@Master ~/workspace/testProject $
```

**Comment by mikermcneil** [comment] 2015-09-23 03:02
Hi @shaunstanislaus - what version of node and NPM are you using?

**Comment by shaunstanislaus** [comment] 2015-09-23 03:12
the latest

```bash

shaunstanislaus@Master ~/workspace/testProject $ node -v
v4.1.0
shaunstanislaus@Master ~/workspace/testProject $ npm -v
3.3.3
shaunstanislaus@Master ~/workspace/testProject $


```

**Comment by wulfsolter** [comment] 2015-09-23 03:30
Posted workaround in https://github.com/balderdashy/sails/issues/3253 until express/connect play better

**Comment by listx** [comment] 2015-09-23 08:55
Could this be a dupe of #3176 ?

**Comment by mikermcneil** [comment] 2015-09-24 01:20
> Posted workaround in #3253 until express/connect play better

@wulfsolter thanks!


> Could this be a dupe of #3176 ?

@listx :+1:  @shaunstanislaus Would you try again with v0.11.2 and let us know how it goes?  Merging this issue w/ https://github.com/balderdashy/sails/issues/3176

**Closed by mikermcneil** 2015-09-24 01:20 UTC

**Comment by shaunstanislaus** [comment] 2015-09-24 01:45
@mikermcneil  you mean v0.11.2 sails? 

when will you release v0.11.2 ?

**Comment by tjwebb** [comment] 2015-09-24 01:46
Sails 0.11.2 is released: https://www.npmjs.com/package/sails

**Comment by shaunstanislaus** [comment] 2015-09-24 02:11
@tjwebb , it worked. is weird, i just installed sails globally a day before, and now the 11.2 is released.

```bash
shaunstanislaus@Master ~/workspace/testProject $ sails -v
0.11.2
shaunstanislaus@Master ~/workspace/testProject $ sails lift

info: Starting app...

info:
info:                .-..-.
info:
info:    Sails              <|    .-..-.
info:    v0.11.2             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------'
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info:
info: Server lifted in `/Users/shaunstanislaus/workspace/testProject`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Thu Sep 24 2015 10:09:04 GMT+0800 (CST)

debug: Environment : development
debug: Port        : 1337
debug: -------------------------------------------------------
```

**Comment by luish000** [comment] 2015-09-24 02:19
This version comes with es6 support, doesn't it??
