### ISSUE TITLE
IE11 Quirks Mode and Req.wantsJSON not honored

### ISSUE THREAD

**Issue by crh3675** [balderdashy/sails#2764] opened 2015-03-19 13:36 UTC
I ran into an interesting bug when using req.wantsJSON.  When I turned on certain compatibility mode settings in IE11 (Display intranet sites in compatibility mode), the framework always wants to send JSON instead of rendering an HTML view.  I presume this has something to do with the request headers that are sent.

Perhaps there are a couple headers that the framework doesn't account for that are are naturally missing in compatibility mode which causes this behavior.  

To replicate, make a controller with an action (abbreviated):
````
index : function(req, res) {
   if(req.wantsJSON) {
     res.json({ 'message' : 'I am JSON'});
   } else {
     res.send('I am HTML');
   }
}
```

Then, toggle the compatibility settings in IE.  In every case that I tested, only JSON ever was returned and IE is so stupid it wants the user to download the JSON file.

**Comment by tjwebb** [comment] 2015-03-23 02:35
Is this a bug in IE, then? I'm not sure how to go about solving this.

**Comment by crh3675** [comment] 2015-03-24 11:43
I think the implementation for wantsJSON isn't thorough enough to catch that mode/request header settings.  I can inspect the headers some more to see what is missing that wantsJSON expects.

**Comment by crh3675** [comment] 2015-03-24 13:02
Ok, here are the request header differences

Compatibility On
========================
	Key	Value
	Request	GET /session/new HTTP/1.1
	Accept	application/x-ms-application, image/jpeg, application/xaml+xml, image/gif, image/pjpeg, application/x-ms-xbap, application/vnd.ms-excel, application/vnd.ms-powerpoint, application/msword, */*
	Accept-Language	en-US
	User-Agent	Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)
	Accept-Encoding	gzip, deflate
	Host	itcosandbox01:18013
	Cookie	sails.sid=s%3AAHihQY8SwBfw3YbvmiRnMMCV.PnKKqWECaudA8fRjA1Hf2waqss0cVxpPctwyBe81XPs
	Connection	Keep-Alive
	Cache-Control	no-cache
	DNT	1


Compatibility Off
========================
	Key	Value
	Request	GET /session/new HTTP/1.1
	Accept	text/html, application/xhtml+xml, */*
	Accept-Language	en-US
	User-Agent	Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
	Accept-Encoding	gzip, deflate
	Host	itcosandbox01:18013
	Cookie	sails.sid=s%3AAHihQY8SwBfw3YbvmiRnMMCV.PnKKqWECaudA8fRjA1Hf2waqss0cVxpPctwyBe81XPs
	Connection	Keep-Alive
	Cache-Control	no-cache
	DNT	1

**Comment by crh3675** [comment] 2015-04-08 00:18
Can we look into this more? I think we need to add:

```
req.isQuirkyBrowser = (accept.indexOf('x-ms-application') !== -1);

req.wantsJSON = req.xhr;
req.wantsJSON = req.wantsJSON || req.isSocket;
req.wantsJSON = req.wantsJSON || (!req.explicitlyAcceptsHTML && !isQuirkyBrowser);
req.wantsJSON = req.wantsJSON || (req.is('json') && req.get('Accept'));
req.wantsJSON = req.wantsJSON || req.options.wantsJSON;
```

**Comment by randallmeeker** [comment] 2015-04-08 02:15
I think the solution is that you manually have to set the header ```X-Requested-With``` to ```XMLHttpRequest``` in your client.

**Comment by crh3675** [comment] 2015-04-08 11:40
@randallmeeker the problem is that I don't want JSON and the client is native IE browser with compatibility mode that IS NOT requesting via XmlHttpRequest

**Comment by crh3675** [comment] 2015-04-08 11:43
By the way, Compatibility On in IE is the quirks mode.

**Comment by tjwebb** [comment] 2015-04-08 13:51
So is this an issue in IE or in sails.js?

**Comment by randallmeeker** [comment] 2015-04-08 14:48
Oh I understand now, so the issue is that Sails is assuming that if the request is not explicitly asking for HTML then is must want JSON. 

This may not be a bug but the world in which Sails.js is supposed to exists. It could be argued that Sails is an API first so when all else fails it would and should deliver JSON. 

@crh3675's Solution would work, but I would also ask if it is necessary? Compatibility mode was created so newer versions of IE could view older websites. This is a brash assumption to make, but can't we assume that Sails apps being created are being done with modern standards and that their should be no reason to view a sails website with compatibility view? <--- this is not a rhetorical question, I'm genuinely looking for examples as I am curious.

**Comment by tjwebb** [comment] 2015-04-08 17:03
> It could be argued that Sails is an API first so when all else fails it would and should deliver JSON.

That'd be my argument. If we change this behavior, someone else will complain that by default they are getting html when they really want json. And I'd agree with them.

**Comment by crh3675** [comment] 2015-04-08 23:26
Unfortunately, we have some internal applications (government specific) that require that Compatibility Mode setting to be turned on for all users using IE.  I would present that probably a good 20k+ developers and users employed by Federal Government contracts deal with this awkward necessity.

As much as I enjoy how much SailsJS is progressive, a lot of government applications are not as progressive. The alternative is to avoid using __wantsJSON__ knowing that it breaks in quirks mode for IE.

**Comment by crh3675** [comment] 2015-04-08 23:33
If it is not a proposed core change, perhaps a global config that someone can override?

**Comment by randallmeeker** [comment] 2015-04-08 23:43
Hmmmm, @crh3675 has a point, and the code is poorly written to provide for an override in how it really really really wants to default to JSON. It makes the case that unless you ask for html your getting json, when quirks mode can't ask for HTML. 

However, it is the response files which uses ```wantsJSON``` to determine the response type and these files ```responses/**.js``` are made to be customized. You could easily modify it to serve the correct file based on any criteria. Or for that matter you could easily replace ```req.wantsJson``` with your own function in middlewhere or a policy.  

I'm not saying a core change may not be warranted but their also seems to be an easy non-core fix as well.

**Comment by crh3675** [comment] 2015-04-08 23:55
Perhaps we can label for documentation? Thanks for taking the time to consider the options.

**Comment by tjwebb** [comment] 2015-04-09 04:12
> Unfortunately, we have some internal applications (government specific) that require that Compatibility Mode setting to be turned on for all users using IE.

That sounds exhausting, I'm sorry. We will try to help however we can, but I can't justify sullying the core to accommodate IE quirks mode. Let's try to build this workaround in a module or hook that can be added on to sails; this is certainly something we want sails.js to be able to do.

> Nuts and bolts, it is a Sails.js issue because Sails.js assume a perfect world :-)

Condolences aside, I understand that the world is a maddening and ridiculous place, but we if we merged in every fix like this that everyone needs for whatever horribleness they have to deal with at their jobs, sails.js would be an [unusable mess](http://en.wikipedia.org/wiki/Tower_of_Babel). We don't assume the world is perfect, but we're not going to wholly bend to its craziness either.

@crh3675 can you look into see if you can alter this functionality via a hook of some sort using @randallmeeker's suggestions as a guide?

**Comment by crh3675** [comment] 2015-04-09 10:34
@tjwebb fair enough.  I will look into implementing a hook and provide the solution that I cam up with.

**Comment by tjwebb** [comment] 2015-04-09 10:39
@crh3675 that'd be greatly appreciated, and we'd be happy to share the fix for anyone else who might have the same issue.

Closing for now

**Closed by tjwebb** 2015-04-09 10:39 UTC
Labels: help wanted, needs documentation, question
