### ISSUE TITLE
Sails (Express) breaks on npm 3.3.3

### ISSUE THREAD

**Issue by wulfsolter** [balderdashy/sails#3253] opened 2015-09-23 03:18 UTC
With node v4.1.0 and npm 3.3.3 express's prereq connect is not symlinked properly, resulting in a failure to start sails:

Error message when launching Sails:
```
$ node app.js
info: *** Starting Sails in undefined ***
module.js:338
    throw err;
    ^

Error: Cannot find module 'express/node_modules/connect'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/wulfsolter/Code/wherewolf-backend/node_modules/sails/lib/hooks/session/index.js:25:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/wulfsolter/Code/wherewolf-backend/node_modules/sails/lib/app/configuration/index.js:63:34
    at /Users/wulfsolter/Code/wherewolf-backend/node_modules/sails/node_modules/lodash/dist/lodash.js:3741:15
    at forOwn (/Users/wulfsolter/Code/wherewolf-backend/node_modules/sails/node_modules/lodash/dist/lodash.js:2106:15)
    at Function.reduce (/Users/wulfsolter/Code/wherewolf-backend/node_modules/sails/node_modules/lodash/dist/lodash.js:3738:9)
    at Configuration.defaultConfig (/Users/wulfsolter/Code/wherewolf-backend/node_modules/sails/lib/app/configuration/index.js:58:18)
```

Workaround is to relink connect:
    ln -s ../../connect/ node_modules/express/node_modules/

**Comment by shaunstanislaus** [comment] 2015-09-23 03:49
@mikermcneil  i can't see the full link of his relink.

**Comment by listx** [comment] 2015-09-23 08:55
Could this be a dupe of #3176 ?

**Comment by sgress454** [comment] 2015-09-23 16:25
@listx yup, thanks!  Closing in favor of #3176

**Closed by sgress454** 2015-09-23 16:25 UTC
