### ISSUE TITLE
Binding services to the module context breaks static properties on methods.

### ISSUE THREAD

**Issue by natecavanaugh** [balderdashy/sails#2665] opened 2015-02-18 00:05 UTC
Hi there,
This was working in 10.4, but in 11, as of 97861aa30da56eef2907516010ac31157e8c3abe there is a use case that is broken.
Let's say we have `EmailService.js`
```
var EmailService = function(){
// Do some stuff
};
EmailService.foo = 'Some Value';
module.exports = EmailService;
```

When the module loader is calling _.bindAll, it's replacing all methods on the object with a "bound" version, but it completely wipes out any existing properties on that function.

It could be all well and good to say "Don't export functions", but 1. it does it to every function on the object, not just the exported one (so if `EmailService.foo` were a function, and had properties, those would be wiped out as well), and 2. we may be exporting a third party library, where we don't control the kind of object that's being exported.

Since `_.bindAll` is destructive, I would suggest making this something the service can opt into or control themselves.

**Comment by sgress454** [comment] 2015-03-01 07:44
> When the module loader is calling _.bindAll, it's replacing all methods on the object with a "bound" version, but it completely wipes out any existing properties on that function.

That would be terrible!  Fortunately the exact code you posted works fine for me on a fresh install of v0.11 (tried `EmailService.foo` in `sails console`, as well as `console.log(EmailService.foo)` inside of the function), so I suspect the issue is elsewhere.

**Comment by natecavanaugh** [comment] 2015-03-06 22:46
Sorry, for some reason I thought I had tested the example thoroughly, but testing it, you are correct. Where it fails is the following example:
```
var EmailService = function(){
// Do some stuff
};
EmailService.SomeFn = function() {
	// Do some other stuff
};
EmailService.SomeFn.foo = 'Some Value';
module.exports = EmailService;
```

So basically, if the property on the function is also a function that contains properties, those props are lost.

Are you able to reproduce the same issue?

Thanks again for looking at it :)

**Comment by sgress454** [comment] 2015-03-06 23:06
Ok, that I can reproduce, and it makes sense.  I suppose this is more an issue with Lodash's `_.bindAll` function than with Sails core, but that's neither here nor there.  Can you work around it?  Is it imperative that your service functions have their own properties?  Or could you just store those properties in a hash at the top level of the service, or better yet in a private var that doesn't get exported at all?

**Comment by natecavanaugh** [comment] 2015-03-07 20:19
Thanks for the response, but I don't know if I can work around it for all of my scenarios, as it's a third party lib that's exposing utility methods on a function that also does some work on it's own.
For the immediate case, I'm pretty sure I can work around this one method, but not the others, and I have a feeling I'll hit it again.
That being said, please feel free to close this out if you feel so inclined, though it may be useful to keep it open so I don't reopen another one when I run into an issue that is a permanent blocker :)

Thanks again for looking at this!

**Comment by sgress454** [comment] 2015-03-07 20:40
Actually, it seems to me that we don't need to be running `_.bindAll` on modules that export functions.  The intention is to make sure that any methods exposed by the service (or controller, model, etc.) have access to the `sails` instance using `this.sails`.  If you're exporting a function, we can just use regular `_.bind` on it, which should leave its properties alone.  If any of those properties happen to be functions themselves, they won't have `this.sails`, but that's okay because 1) you can add it yourself, and 2) in a lot of cases (yours included) they'll be from a 3rd party that doesn't need a reference to Sails anyway.  Sound right?

**Comment by natecavanaugh** [comment] 2015-03-09 16:26
I think it sounds right, except for `_.bind` portion leaving alone properties, unless there is something else going on that I'm not aware of.
`_.bind` should return an entirely different function instance, and as far as my understanding of underscore and lodash go, they don't copy properties of the function over, for instance here:
```
var foo = {
  bar: function(){console.log('foo.bar', this, arguments);}
};
foo.bar.baz = 1;
foo.bar = _.bind(foo.bar, g);
foo.bar.baz; // is undefined
```

But it's possible I don't know the whole picture, since AFAIK, calling `_.bindAll` should technically do the same, but it seems it's not from what I can tell.
Out of curiosity, do you know why it's ignoring leaving properties alone in these cases?

Thanks again for your responses :)

**Comment by lmacsen** [comment] 2015-03-30 11:10
Hi there,

I have same problem but I think i'll end it up by appending all to an extra object (mongoose in my case):

```javascript
module.exports = {
  mongoose: {
    User: require('../models/User.js')(mongoose),
  }
};
```

**Comment by natecavanaugh** [comment] 2015-04-08 20:15
Any info on why this was closed? It doesn't appear to be actually fixed.

**Comment by mikermcneil** [comment] 2016-01-17 21:51
@natecavanaugh [sorry about that](https://github.com/balderdashy/sails/issues/3478)!  I just stumbled across this issue- sorry for the slow reply.

@natecavanaugh I appreciate you taking the time to get to the bottom of what's breaking.  Could you provide more details about your use case?  In order to make a change like this, it's helpful to know more about how you're using your services (see    https://github.com/balderdashy/sails/blob/master/CONTRIBUTING.md#v-proposing-features-and-enhancements for more background)

@lmacsen would you mind posting more about your use case?  Also, re mongoose:  you might want to [check this out](https://github.com/mikermcneil/sails-hook-orm-mongoose)

**Comment by mikermcneil** [comment] 2016-01-17 22:05
@natecavanaugh By the way, to give my question some more context-- my hope is that this is something we can address via a configuration option (philosophically, you should be able to tell Sails to leave your services alone, but binding is also useful in the general case).  What I'm looking for is stuff like "Where are you calling your service from?" , "What is the function that's getting its winged clipped _supposed_ to do?", and "Why would a workaround not be appropriate in your case?" Thanks again!

**Comment by sgress454** [comment] 2016-01-18 04:15
Not sure why this got closed either.  The reasoning behind binding module methods to the module is to make sure they have access to the Sails instance they're running in, even if globals are turned off.  This allows Sails apps to be included as dependencies (and just allows you to turn `sails.config.globals` off if you need to).

The flipside is that if you have a Sails service like:

```
module.exports = {
  someSweet3rdPartyToolMethod = require('tool')
};
```

and that third-party function has properties, or expects its context to be that of the 3rd party module, you're in trouble.  And since it's very unlikely that the third-party library would expect to have access to Sails as `this.sails`, it'd be perfectly safe for it not to be bound.  As @mikermcneil hinted at, a configuration setting to toggle this behavior could be the right answer, but it would probably have to apply to _every_ method in the module--having it be more selective would make things pretty complicated and entangled.  In the worst case scenario where you've cooked up some service that needs to have untouched, 3rd party methods mixed with methods that need access to Sails, you can do something like:

```
module.exports = function(sails) {

   return {

      myMethod: function(foo) {...},
      3rdPartyMethod: require('tool');

   };

};
```

and call methods with `MyService(sails).myMethod();`

**Comment by mikermcneil** [comment] 2016-01-18 13:40
@sgress454 Good points!

> and call methods with MyService(sails).myMethod();

@natecavanaugh for the record, this is what Sails core does internally in many cases.

**Comment by mikermcneil** [comment] 2016-01-27 04:55
Unless @natecavanaugh or anyone else has any immediate objection or is interested in writing up a full proposal for the config option to control this pretty quickly, let's plan to leave this behavior as is for 0.12, but then tentatively plan to remove the automatic binding of context for Sails v1.0.

cc @sgress454

**Comment by mikermcneil** [comment] 2016-01-27 07:01
see also https://github.com/balderdashy/sails/pull/2910  (this was merged, then later reverted- not sure what the intent was there.  Either way, it would to be rebased, and it would need accompanying changes to docs.  It does contain tests!)

**Comment by mikermcneil** [comment] 2016-01-31 20:42
@natecavanaugh Went ahead and opened a very simplistic proposal for this to make sure it stays on our radar: https://github.com/balderdashy/sails/pull/3536

@everyone:  We could really use help to get this done for Sails v1.0, so if you're interested in contributing, please check out that pull request above.  Thanks!

**Closed by mikermcneil** 2016-01-31 20:42 UTC
Labels: inconsistency

**Comment by natecavanaugh** [comment] 2016-02-29 23:37
@mikermcneil Sorry for ***my*** late reply :)
But I think that's fine for now (I was able to switch out some of the functionality for another lib), but I'm happy to hear it's on the radar :)

Thanks again!
