### ISSUE TITLE
Sails 0.12.0-rc6 debug error : Segmentation fault

### ISSUE THREAD

**Issue by chirag200666** [balderdashy/sails#3538] opened 2016-02-01 22:35 UTC
When I am running sails with node-inspector then I am getting Segmentation fault error.
I ran the sails app using the command : `node --debug app.js`
and ran node inspector using `node-inspector`  
The app is lifted and the bootstrap code runs but after that it gives the segmentation fault error

I also tried the debugging using the command  `node-debug app.js --save-live-edit=true`
here the debugger is started, since the default breakpoint being set to the first line of app.js it stops there, after continuing  runs on few files and then it is detaches from the app.

Then I setup breakpoints in the code by writing `debugger` and run the app using `sails debug` , the app lifts, but when I try to access the url of controller where I set the breakpoint the app crashes without giving any error. 

Using sails version :  0.12.0-rc6 
Node version : 4.2.6

I updated sails to rc6 version because of grunt issue( #2670 ) in the 0.11.4 version.

**Comment by sgress454** [comment] 2016-02-02 21:50
Hi @chirag200666, thanks for the report.  It's hard to say what's going on without more information.  Would you mind setting up a repo that reproduces this in a new sails app? 

e.g.:
```bash
sails new sails-issue-3538
cd sails-issue-3538
# Now make whichever are the simplest/quickest changes which reproduce the issue,
# and when you for sure have the issue isolated, run:
git init
hub create  # or use the GitHub UI to create the repo and `git remote add` it manually
git add .
git commit -am 'Reproduces https://github.com/balderdashy/sails/issues/3538'
git push -u origin master
hub browse # or open the repo in your browser manually
# Then copy the URL of the new repo and paste it as a comment on this issue.
# We'll check it out, and since this way we'll be able to experience the problem
# ourselves, we should have no problem getting to the bottom of it.
```

Thanks!

**Comment by LongSteve** [comment] 2016-02-04 19:39
I hit this same issue today.  I think it's related to this Node issue https://github.com/nodejs/node/issues/4440

One comment says that if you roll back to Node v4.2.4, that fixes the issue, but that might be awkward depending upon how you install Node.

In Sails, I got around the issue by setting **inspect:false** in my log config.  But, since that can be useful when running normally, I actually did this in log.js:

```
var inspectOk = !(typeof v8debug === 'object');
module.exports = {
  log: {
    inspect: inspectOk
  }
}

```
This turns the inspect feature off when running in the debugger

**Comment by chirag200666** [comment] 2016-02-05 06:56
Hi @sgress454 
I created the issue repo : https://github.com/chirag200666/sails-issue-3538
using node-inspector while debugging the app should give the error.

To replicate the issue I had created an api and added a create query in bootstrap.js (somethings like `User.create({'name':'Ram'}).exec( console.log);` ) and then the segmentation fault issue occurs. Few observations I made, when I keep bootstrap.js empty the issue doesn't come, when I remove console.log from bootstrap.js then the issue doesn't come, hope it helps.
using node version: 4.2.6

Thanks

**Comment by chirag200666** [comment] 2016-02-05 06:57
@LongSteve changing the log.js file ( config/log.js ?) didn't fix the issue for me. But downgrading node to 4.2.4 allows me to debug, thanks for your help.

**Comment by mikermcneil** [comment] 2016-02-05 12:21
@LongSteve thanks for the tip, and the link to the issue in Node.  That helps a ton.

@chirag200666 really appreciate the repro-- and thanks for trying this out w/ 4.2.4!  Unfortunate that the log config fix doesn't solve it.  Looks like Myles pushed a fix in Node core, so this should be resolved again soon.

**Comment by mikermcneil** [comment] 2016-02-05 12:33
To summarize for anyone reading this, if you run into this error, the solution (as of Friday February 5th, 2016) is to downgrade to node version 4.2.4.

Will keep this open until https://github.com/nodejs/node/pull/4819 in Node core is merged and published, and we've confirmed that the new version solves this problem.

**Comment by sgress454** [comment] 2016-02-07 16:27
nodejs/node#4819 has been merged.  Not published yet, but should be in the next release.

**Comment by sgress454** [comment] 2016-02-10 20:24
Node 5.6.0 was released yesterday.  It doesn't list this specific issue in the changelog, but that doesn't mean it didn't make it in.  Would someone mind checking with the new Node and seeing if the issue persists?

**Comment by sgress454** [comment] 2016-02-12 16:28
Update: works for me w/ Node 5.6.0 (I was able to repro w/ 4.2.6).  If anyone still has problems, feel free to post here and we'll re-open.

**Closed by sgress454** 2016-02-12 16:28 UTC
Labels: bug, node version issue, try this out please
