### ISSUE TITLE
Sails socket authentication (using passport)

### ISSUE THREAD

**Issue by tomercagan** [balderdashy/sails#4053] opened 2017-03-22 12:02 UTC
**Sails version**: 0.12.11
**Node version**: v6.9.5
**NPM version**: 3.10.10
**Operating system**: Windows 10

<hr/>

Hi,

I am trying to implement authentication for sockets. My "plan" is to reuse (as much as possible) passport authentication. I've searched online and even posted in SO ([here](http://stackoverflow.com/questions/42765635/sails-socket-authorization-using-passport)) but so far, to no avail.

My flow is as follows - the user logs in (or authenticate via token) and once a valid JWT token is available, makes a connection (via io.sails.connect). I have a policy that uses JWT which works both for socket and for HTTP requests. This works fine.

Next, I want to not allow users who are not authenticated to even connect with socket.io so I am trying to figure out how to do it.

What I am doing (to facilitate the socket authorization using the "jwt" policy) is as follows - after authentication, I am setting the URL and headers on io.sails and then use the connect method to connect:

    io.sails.url = connections.http.baseURL;

    io.sails.headers = {
        'Authorization': 'Bearer ' + token
    };
    io.sails.useCORSRouteToGetCookie = false;

    io.socket = io.sails.connect();
    io.socket.on('...', someHandler);

While this works for the authorization (I see the authorization header in socket requests) it doesn't work for the socket connection - when looking at the `handshake` object on the `beforeConnect` handler, I don't see the authorization header:

> {
  "host": "localhost:8080",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0",
  "accept": "*/*",
  "accept-language": "en-US,en;q=0.5",
  "accept-encoding": "gzip, deflate",
  "origin": "null",
  "cookie": "io=XiMD7-tD392tofJhAAAW; mongoMachineId=7498040; sails.sid=s%3A4eSb3wurcSc0hfzroA1C40o77dH2oPjl.QxP2Ba%2FTAG%2BqfCzezCvou8X9DtEyQ8gB0lzCai3E4O4",
  "connection": "keep-alive"
}

Next, I've tried to add a query to the connect method:

    io.socket = io.sails.connect({token: token});

In this case, I see the token under `handshake._query` and not `handshake.query` or as documented (here) `socket.handshake.query`.

This makes me suspect that either I don't understand or missing something, or that the documentation as a little off...

Any suggestions / pointers? Am I doing something wrong or missed something?

Another thing - assuming all the things above are sorted out, will I even be able to use a passport strategy here? I know that in general passport expects a request (IncomingMessage) object to work with... I believe passport (depending on configuration) will expect a `query` or `body` for getting the token or will look for it in headers.

**Comment by sgress454** [comment] 2017-03-27 14:29
Hi @tomercagan -- have you tried [initialConnectionHeaders](http://sailsjs.com/documentation/reference/web-sockets/socket-client/sails-socket/properties#?advanced-properties)?

**Comment by tomercagan** [comment] 2017-03-27 16:22
Hi @sgress454 

I haven't - I am very disciplined and per the docs ([here](http://sailsjs.com/documentation/reference/web-sockets/socket-client/sails-socket/properties)) it says it is for node.js only (i.e. using the client in a node.js script):

> Node.js only--not available in browser. Dictionary of headers to be sent with the initial connection to the server

I'll give a try though :-)

**Comment by sgress454** [comment] 2017-03-27 16:34
@tomercagan no, you're completely right, I forgot about that.  Let me think on this, I'm sure there's a way (or a good reason why there isn't one) to specify headers for the initial connection...

**Comment by tomercagan** [comment] 2017-03-27 16:35
So - I tried and this does not work :-(

Also, I am using both polling and websecket and the initial connection is polling (if that matters).

I am not sure if I am doing something wrong, there's a problem with the code or there's a problem with the docs (or something else).

Should it matter whether I set the properties in the `<script>` tag or through code? (not that I can do otherwise since I need a token which is only available after the user logged in but at least it can give some direction).

Any suggestions/comments?

**Comment by sgress454** [comment] 2017-03-27 16:56
Ok, found it -- the issue is that historically, socket.io did not pass along headers from the browser during the initial socket connection (apparently it's not part of the websocket spec), so in Sails we give you that warning when using `initialConnectionHeaders` so you wouldn't be surprised about it not working from `sails.io.js`.  Check out this issue for some workarounds people have used in the past:

https://github.com/socketio/socket.io-client/issues/976

Now, that having been said, it looks like they have implemented a solution for this in the latest socket.io dependencies using `transportOptions`, although I haven't gotten that to work in some quick tests.  It may require some updates to `sails.io.js`.  I'm going to close this since it's not a bug in the framework, but I'll post back here if I find anything re: `transportOptions` that will help you.

**Closed by sgress454** 2017-03-27 16:56 UTC

**Comment by tomercagan** [comment] 2017-03-27 17:12
What about the query parameters not being available in `handshake.query` or `socket.handshake.query` in the `beforeConnect` socket lifecycle callbacks? That is also expected?

**Comment by sgress454** [comment] 2017-03-27 17:48
@tomercagan

> What about the query parameters not being available in handshake.query or socket.handshake.query in the beforeConnect socket lifecycle callbacks?

Is there somewhere in the Sails docs where we talk about what you can expect in `handshake`?  If there is, we should probably update it to point somewhere in the socket.io docs.  It does appear that they [changed this from `handshake.query` to `handshake._query`](https://github.com/socketio/socket.io/issues/1557), although even after jumping from issue to issue in that thread I don't quite know why :-/

**Comment by sgress454** [comment] 2017-03-27 18:01
Nevermind, I see it: http://sailsjs.com/documentation/reference/web-sockets/socket-client/sails-socket/properties#?advanced-properties

It's still correct for controllers, but for the lifecycle callbacks like `beforeConnect` it should be `handshake._query` now.  I'll go ahead and update that, thanks for the heads-up!

**Comment by tomercagan** [comment] 2017-03-28 13:42
Hi, thanks for the info. If you have further information / updates - I'd be happy to hear.

My first intent was using passport.js to authenticate the connection (using JWT) as I was sure the handshake would be similar to a request (`IncomingMessage`?) but without `headers` or a `query` I am not sure that is possible.

Do you have any thoughts about that? Would it be possible to do? Should I open a request for enhancement or it doesn't make sense?

(My intention was to reuse the passport.js code, not having to duplicate it with my own code).
