### ISSUE TITLE
npm install fails with error

### ISSUE THREAD

**Issue by danielbaak** [balderdashy/sails#3286] opened 2015-10-05 14:24 UTC
after creating a new sails *v0.11.0* project with `sails new sailsTest` running npm install breaks with the following error:

    ➜  sailsTest  npm install
    npm ERR! Linux 3.13.0-37-generic
    npm ERR! argv "/usr/bin/nodejs" "/home/user/.npm-packages/bin/npm" "install"
    npm ERR! node v4.1.1
    npm ERR! npm  v3.3.3
    
    npm ERR! Cannot set property 'lodash' of undefined
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>
    npm ERR! Linux 3.13.0-37-generic
    npm ERR! argv "/usr/bin/nodejs" "/home/user/.npm-packages/bin/npm" "install"
    npm ERR! node v4.1.1
    npm ERR! npm  v3.3.3
    
    npm ERR! Cannot set property 'fs-extra' of undefined
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /tmp/sailsTest/npm-debug.log

The issue doesn't occur with other npm versions than *npm v3.3.3*.

**Comment by randallmeeker** [comment] 2015-10-05 14:38
this is what I got with #3281

**Comment by sgress454** [comment] 2015-10-09 15:35
Yup, dupe of #3281.  Thanks @randallmeeker.

**Closed by sgress454** 2015-10-09 15:35 UTC
