### ISSUE TITLE
Are there any plans to move to gulp?

### ISSUE THREAD

**Issue by adnan-kamili** [balderdashy/sails#3306] opened 2015-10-14 13:47 UTC
Do you have any plans to replace grunt with gulp as the default task runner. I would love to see that.

**Comment by randallmeeker** [comment] 2015-10-14 13:59
Duplicate of . . . most of these https://github.com/balderdashy/sails/search?q=gulp&type=Issues&utf8=%E2%9C%93

**Closed** 2015-10-15 17:30 UTC
