### ISSUE TITLE
"sails debug" on node v0.12.0 throwing error EADDRINUSE

### ISSUE THREAD

**Issue by MikeCostello** [balderdashy/sails#2670] opened 2015-02-19 23:00 UTC
Running Sails v0.11.0 and Node v0.12.0

When I run
```
sails new app; cd app
sails debug
```

Console logs...

```
error: Grunt :: Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Agent.Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Agent.Server.listen (net.js:1240:5)
    at Object.start (_debugger_agent.js:20:9)
    at startup (node.js:86:9)
    at node.js:814:3
```
No conflicting ports were listening prior to running sails.
Looking at travis.yml is only node v0.10.x supported currently?

**Comment by Kikobeats** [comment] 2015-02-19 23:25
at this moment sails pass the tests for 0.10.x, so I think that is not possible run your code under 0.12 because is not officially supported... 

(Although I do not think that error is the version of node).

**Comment by tjwebb** [comment] 2015-02-20 15:24
> error: Grunt :: Error: listen EADDRINUSE

There's only one way this happens. It's if your port is already being used by another program.

**Comment by MikeCostello** [comment] 2015-02-20 15:48
Agreed, but this is the output just prior to launching ```sails debug```
```
lsof -i -P | grep -i "listen"

redis-ser  678 mikecostello    4u  IPv6 0x704352d066f66a57      0t0  TCP *:6379 (LISTEN)
redis-ser  678 mikecostello    5u  IPv4 0x704352d06e87f7d7      0t0  TCP *:6379 (LISTEN)
postgres  1604 mikecostello    5u  IPv6 0x704352d066f68357      0t0  TCP localhost:5432 (LISTEN)
postgres  1604 mikecostello    6u  IPv4 0x704352d07074ad67      0t0  TCP localhost:5432 (LISTEN)
postgres  1604 mikecostello    7u  IPv6 0x704352d066f66f57      0t0  TCP localhost:5432 (LISTEN)
GitHub    8261 mikecostello   15u  IPv4 0x704352d07dc24d67      0t0  TCP localhost:25035 (LISTEN)
GitHub    8261 mikecostello   16u  IPv6 0x704352d066f67957      0t0  TCP localhost:25035 (LISTEN)
```

After running ```sails debug``` the debug port is opened and I can connect with node-inspector. Just the error is logged in the console.

Node v0.10 & Sails v0.11 works
Node v0.12 & Sails v0.10.5 same error

**Comment by tjwebb** [comment] 2015-02-20 21:29
Hmm. It's also not clear to me why the error appears to come from Grunt, and not the debugger. Can you disable Grunt and try again?

**Comment by MikeCostello** [comment] 2015-02-20 21:51
With Grunt disabled no error

**Comment by wewoor** [comment] 2015-02-28 09:30
I have the same problem, how to solve it... console will output *Error: listen EADDRINUSE*  When i'm run 
> node-debug app.js 
,And the Node Inspector not work correctly. 
>My node version:v0.12.0
>sails: v0.10.5
it's too bad not this tool.

**Comment by Patrick64** [comment] 2015-03-02 21:40
I'm getting the same, it prevents assets from copying to .tmp/public. I've tried changing the ports as follows but it's still giving the error.
`node-debug --debug-port=3333 --web-port=4444 app.js`

**Comment by nicco** [comment] 2015-03-05 18:44
Same here, node 0.10 fine 0.12 i get the error...

**Comment by konstantinzolotarev** [comment] 2015-03-07 16:27
+1 for this issue.

**Comment by nehalmehta** [comment] 2015-03-12 02:49
Same issue when running Sails v0.11.0 and Node v0.12.0

**Comment by chemjournal** [comment] 2015-03-18 16:56
I seem to have the same problem... Anyone found a fix yet?

**Comment by nicco** [comment] 2015-03-18 16:58
Node 0.10.x
Is the only option

**Comment by MikeCostello** [comment] 2015-03-18 17:50
@tjwebb comment disabling grunt avoids the error if your project doesn't need that hook.

http://sailsjs.org/#!/documentation/anatomy/myApp/sailsrc.html
```
{
 "hooks": {
    "grunt": false
  }
}
```

**Comment by DrMoriarty** [comment] 2015-03-21 10:19
+1 for this issue.

**Comment by bmwertman** [comment] 2015-03-22 18:29
Any new info on this? I am getting the same error.

node --version
v0.12.0

sails --version
0.11.0

**Comment by bmwertman** [comment] 2015-03-22 19:55
`npm cache clean` and  `npm install node-inspector` as mentioned [here](https://github.com/node-inspector/node-inspector/issues/535) fixed the "cannot find module" error. But I'm still seeing the EADDRINUSE error as everyone else.

**Comment by willSonic** [comment] 2015-03-23 02:30
I am using Gulp, using sails-generator and I am getting the same error..
error: Gulp :: Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Agent.Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Agent.Server.listen (net.js:1240:5)
    at Object.start (_debugger_agent.js:20:9)
    at startup (node.js:86:9)
    at node.js:814:3

**Comment by tjwebb** [comment] 2015-03-23 02:41
can someone share a project I can clone to see this in action? I cannot reproduce this

**Comment by WillStreeter** [comment] 2015-03-23 03:12
So I pushed this to a repository even though it is not a fully functional site...

https://github.com/WillStreeter/ang-sails-gulp

I am starting Sails from WebStorm and before it loads I see the above error.

I am using

--$ node -v
v0.12.0
--r$ sails -v
0.11.0

**Comment by tjwebb** [comment] 2015-03-23 03:26
cloned, npm install, works great:
```sh
$ tjwebb@latitude:/.../tjwebb/workspace/ang-sails-gulp (master) $ sails lift

info: Starting app...

info: 
info:                .-..-.
info: 
info:    Sails              <|    .-..-.
info:    v0.11.0             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in `/home/tjwebb/workspace/ang-sails-gulp`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Sun Mar 22 2015 23:24:04 GMT-0400 (EDT)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------
^C
$ node -v
0.10.37
$ sails -v
0.11.0
```

**Comment by WillStreeter** [comment] 2015-03-23 03:27
so you are using 
$ node -v
0.10.37

I was using node 0.12.0

**Comment by tjwebb** [comment] 2015-03-23 03:27
Just tried with node 0.12.0 and iojs 1.6.1 and both work.

**Comment by tjwebb** [comment] 2015-03-23 03:29
Oh I get it, `sails debug` doesn't work.

**Comment by WillStreeter** [comment] 2015-03-23 03:33
Yes.. I was just about to reply that I think that this is the issue because when I run it from the command line with a straight ... sails lift   .. no problems occur but when I run it from the IDE for debugging the error appears

**Comment by tjwebb** [comment] 2015-03-23 03:37
Yea, check this out:
1. `$ nmap -sV 127.0.0.1 -p 5858` says port is closed
2. run sails debug. errors out, but don't close
3. $ `nmap -sV 127.0.0.1 -p 5858` says the port is open, as if `sails debug` is working`. 
4. `sails debug` crashes with `Error: write EPIPE`

So the debugger is actually running. Try running `node debug app.js` instead and see if that works. Looks like `sails debug` needs to be re-tooled.

**Comment by WillStreeter** [comment] 2015-03-23 04:05
So when I run it from webstorm IDE 
with parameter debug... I get 

/usr/local/bin/node --debug-brk=53032 --nolazy debug app.js
Debugger listening on port 53032
debug> < Debugger listening on port 5858
debug> connecting to port 5858... ok
debug> break in app.js:55
 53   // Start server
 54   sails.lift(rc('sails'));
>55 })();
 56 
 57 });
debug>

**Comment by KSanthanam** [comment] 2015-03-26 23:59
I am running node -v 0.12.0
I get the following error 
Error: Cannot find module '/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.2/node-v14-darwin-x64/debug.node

on the console of the browser. when I run 

node-debug --debug-brk --harmony --use-strict app.js

on Mac terminal I get
--
Node Inspector is now available from http://127.0.0.1:8080/debug?port=5858
Debugger listening on port 5858

Starting the interactive shell (REPL). Type `.help` for help.
The module in the current directory was not loaded: Cannot find module '/Users/KK/git/DNetworksAuth'.
Didn't want to start REPL? Run `/usr/local/bin/node-debug .` instead.

I need to run node 0.11.x or above as I am using Web framework koa which needs it.

Please help.

**Comment by felipecm** [comment] 2015-03-27 01:12
+1

**Comment by sirsavary** [comment] 2015-04-03 06:41
+1

**Comment by JameelJiwani** [comment] 2015-04-03 06:51
+1

**Comment by disharmonized** [comment] 2015-04-10 06:28
+1

**Comment by dbuentello** [comment] 2015-04-12 22:01
The issue surfaces between node `v0.11.14` and `v0.11.15`

> Specifically between joyent/node@a2a3fd48934f36d94575dd33d2a2cb732f937f77 and joyent/node@d87480beb29b764ba37cd983b594ad25a406a4c7 
> PR: joyent/node#8476

It appears as if the *bug* has actually been in the codebase since v0.10.x but was undetectable due to how the Grunt process was forked:

```js
// ./node_modules/sails/lib/hooks/grunt/index.js
var child = ChildProcess.fork(

  path.join(__dirname, 'grunt-wrapper.js'),

  [
    taskName,
    '--pathToSails='+pathToSails,

    '--gdsrc='+ pathToSails + '/node_modules'
  ],

  {
    silent: true,       // => setting to false will reveal the bug
    stdio: 'pipe'
  }
);
// Don't forget to comment out the appropriate child.std* listeners
```

Afterwards: 

```sh
Running "watch" task
Waiting...
Failed to open socket on port 5858, waiting 1000 ms before retrying
Failed to open socket on port 5858, waiting 1000 ms before retrying
Failed to open socket on port 5858, waiting 1000 ms before retrying
Failed to open socket on port 5858, waiting 1000 ms before retrying
```

___

##### Possible Solution: 

Looking at the [options](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) for `child_process.fork`,  the `--debug` flag is being passed down to the child upon exiting the womb *i.e. running `sails debug`* :

```js
// ./node_modules/sails/bin/sails-debug.js

// Spin up child process for Sails
Womb.spawn('node', ['--debug', pathToSails, 'lift'], {
    stdio: 'inherit'
});
```

setting `options.execArgv` to an empty array removes the flag and allows the process to continue:

```js
// ./node_modules/sails/lib/hooks/grunt/index.js
var child = ChildProcess.fork(

  path.join(__dirname, 'grunt-wrapper.js'),

  [
    taskName,
    '--pathToSails='+pathToSails,

    '--gdsrc='+ pathToSails + '/node_modules'
  ],

  {
    silent: true,       
    stdio: 'pipe',
    execArgv: []
  }
);
```

**Comment by disharmonized** [comment] 2015-04-14 16:56
Yep. that's worked! Thanks, @dbuentello

**Comment by bmustata** [comment] 2015-04-14 18:59
Same issue in here with Sails v0.11.0 and Node v0.12.0 on Mac OS.

**Comment by bmustata** [comment] 2015-04-15 08:33
Any help will be appreciated on this issue. It's hard not having interactive debugger for node.js applications.

**Comment by disharmonized** [comment] 2015-04-15 14:19
@bmustata but the error EADDRINUSE  has gone after fix?

**Comment by dbuentello** [comment] 2015-04-15 21:01
@bmustata I dont believe are issues are related. Are you using Webstorm?  

While my fix passes testing, `sails debug` doesn't appear to be covered. Im hesistant to submit PR and would classify this as an upstream issue as others have been affected as well (node-inspector has already updated README with info)  Look like fix is on the way. If your interested in tracking issue see:

node-inspector/node-inspector#534
joyent/node#9125
iojs/io.js#877

> While issues are somewhat related, the consesus is that the introduction of new debugger agent has caused many headaches. A rework is on the way.

___

##### Alternate solution:

While technically the underlying problem is unrelated as it was existent in 0.10.0, a PR could be appropriate. Would like to get input from sails team on this.

**Comment by bmustata** [comment] 2015-04-15 21:37
@dbuentello Yes, the debugger it's not working on Webstorm 9 and 10.

Tks and I will monitor the issues closely!

**Comment by asvsfs** [comment] 2015-04-22 14:53
+1 same issue here

**Comment by dustinbolton** [comment] 2015-04-27 21:38
Applied the path by @dbuentello which fixed running "sails debug" from the command line directly. I still cannot run Node inspector with Sails by running "node-debug sails debug" as I get the same type of error:

info: Running app in debug mode...
info: ( to exit, type <CTRL>+<C> )

Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Agent.Server._listen2 (net.js:1146:14)
    at listen (net.js:1172:10)
    at Agent.Server.listen (net.js:1257:5)
    at Object.start (_debugger_agent.js:20:9)
    at startup (node.js:86:9)
    at node.js:814:3

Running "node-debug sails lift" works but of course then breakpoints and other features do not work properly as to be expected. Very frustrating since this worked better with older Node versions. Love input if anyone has any further ideas on getting this working.

**Comment by dapriett** [comment] 2015-04-28 01:04
I'm having issues as well, using Intellij/Webstorm.  WhenI try to debug I get the following:

> /usr/local/bin/node --debug-brk=62497 --nolazy node_modules/sails/bin/sails.js lift
```
Debugger listening on port 62497

info: Starting app...

error: Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 20000)
    at tooLong [as _onTimeout] (/Users/dprietti/AndroidStudioProjects/hydra-respond/node_modules/sails/lib/app/private/loadHooks.js:92:21)
    at Timer.listOnTimeout (timers.js:110:15)

Process finished with exit code 1
```

I also tried this command
> /usr/local/bin/node --debug --nolazy node_modules/sails/bin/sails.js lift
I get the following...
```
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Agent.Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at Agent.Server.listen (net.js:1240:5)
    at Object.start (_debugger_agent.js:20:9)
    at startup (node.js:86:9)
    at node.js:814:3
```

**Comment by tjwebb** [comment] 2015-04-28 03:15
Yea it's a known issue. Anyone who has time to submit a PR would be greatly appreciated.

**Comment by dapriett** [comment] 2015-04-28 03:25
After reading the comments from the io.js issue (https://github.com/iojs/io.js/issues/877) I was able to get debug working with Intellij.

To do so you have to install the early EAP release of Intellij (see comments of https://youtrack.jetbrains.com/issue/WEB-16256#comment=27-979926).  Once installed go to
Help > Find Action... > Registry and uncheck the option "js.debugger.v8.use.any.breakpoint".

This fixed it for me, and the debugger loads up real quick now.

**Comment by dbuentello** [comment] 2015-04-29 15:11
PR submitted @tjwebb

**Comment by tjwebb** [comment] 2015-04-29 16:02
awesome @dbuentello thanks for the PR. I'll take a look.

**Comment by bmustata** [comment] 2015-04-30 07:28
Switched back to node v0.10.38 and all works Ok!

```
node -v
v0.10.38
npm -v
2.5.1
```

**Comment by thomas-lee** [comment] 2015-05-05 14:21
That's fix doesn't work..

    node -v
    v0.12.2
    sails -v
    0.11.0

**Comment by aabluedragon** [comment] 2015-05-20 21:58
+1 having the same issue on node 0.12, works fine on 0.10

**Comment by SlowburnAZ** [comment] 2015-05-22 00:02
Please fix this...  do we really have to use a version of node that is 2 versions behind the latest?

**Comment by tjwebb** [comment] 2015-05-22 02:36
@SlowburnAZ if you'd like to contribute to the PR for resolving this issue, that'd be much appreciated: https://github.com/balderdashy/sails/pull/2888. The core team cannot implement every fix and feature ourselves, we rely on the community to collaborate with us. Thanks.

**Comment by SlowburnAZ** [comment] 2015-05-22 03:09
@tjwebb If I can find the time, I will attempt it.

**Comment by denishgandhi-innoplexus** [comment] 2015-05-25 23:46
Hi,

I am getting same error. 

info: Server lifted in `/var/www/Sails`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Tue May 26 2015 03:30:23 GMT+0530 (IST)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at Array.async.auto.start [as 0] (/var/www/Sails/node_modules/sails/lib/hooks/http/start.js:29:35)
    at /var/www/Sails/node_modules/sails/node_modules/async/lib/async.js:484:38
    at _each (/var/www/Sails/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Object.async.auto (/var/www/Sails/node_modules/sails/node_modules/async/lib/async.js:455:9)
    at Sails.startServer (/var/www/Sails/node_modules/sails/lib/hooks/http/start.js:16:11)
    at Sails.EventEmitter.emit (events.js:92:17)
    at Sails.emitter.emit (/var/www/Sails/node_modules/sails/lib/app/private/after.js:50:11)
    at afterBootstrap (/var/www/Sails/node_modules/sails/lib/app/private/initialize.js:56:11)
    at bootstrapDone (/var/www/Sails/node_modules/sails/lib/app/private/bootstrap.js:51:14)
    at Object.module.exports.bootstrap (/var/www/Sails/config/bootstrap.js:16:3)
    at Sails.runBootstrap (/var/www/Sails/node_modules/sails/lib/app/private/bootstrap.js:44:25)
    at Sails.bound [as runBootstrap] (/var/www/Sails/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)

node -v
v0.10.25
sails -v
0.11.0

Please provide the solution.

**Comment by denishgandhi-innoplexus** [comment] 2015-05-26 00:38
Got it worked by killing process which runs 1337/tcp

sudo fuser -k 1337/tcp
sudo kill 3501

**Comment by Andrew-Max** [comment] 2015-06-29 17:55
+1

**Comment by shaunc** [comment] 2015-07-08 04:31
+1 for fix!

node 0.12.4 ... tried hacking fork per @dbuentello's suggestion ... "works a little" -- ie now I get the error, but if I just wait the debugger somehow limps along, but it acts strangely (e.g. no access to local context in repl).

**Comment by FreCap** [comment] 2015-07-24 09:36
+1 for fix

**Comment by sgress454** [comment] 2015-07-24 15:21
Any chance this fixes it? It just got merged: https://github.com/balderdashy/sails/pull/2888

Someone mind pulling down the latest master branch of Sails and testing?

**Comment by sgress454** [comment] 2015-07-30 16:58
Confirmed working on Node v0.12.7 with the latest Sails patches applied.  Post back here if anyone sees different.

**Closed by sgress454** 2015-07-30 16:58 UTC
Labels: bug, confirmed, help wanted

**Comment by dapriett** [comment] 2015-07-30 17:57
@sgress454 I upgraded to node 0.12.7 - so do we need to wait for sails 0.12.0 release before we see the fix?  Looks like it still does it with sails 0.11.0.

**Comment by sgress454** [comment] 2015-07-30 18:03
@dapriett right--the fix was merged in to the master branch in 88ffc0e, but hasn't been published yet.  We were hoping to get v0.12 out this month but got sidetracked by some non-Sails matters.  Definitely want to get it out ASAP.  In the meantime installing from Github should fix it.

**Comment by ksylvan** [comment] 2015-08-07 03:06
+1 same issue for me.

Sails 0.11.0 and node 0.12.7 with node-inspector 0.12.2.

**Comment by wassimsalib** [comment] 2015-08-17 06:11
+1 Same issue Sails 0.11.0, Node 0.12.7 and node-inspector 0.11.1

**Comment by misterch0c** [comment] 2015-08-18 08:43
+1

**Comment by sgress454** [comment] 2015-08-18 18:14
Ladies and gentlemen, I'm locking this issue.  It's [been solved](https://github.com/balderdashy/sails/issues/2670#issuecomment-126420131).  We'll push out v0.12 as soon as we can, but putting +1 here just obscures the fact that a patch has been made.  You can apply it yourself by replacing your Sails' `/lib/hooks/grunt/index.js` file with the contents of https://raw.githubusercontent.com/balderdashy/sails/88ffc0ed9949f8c74ea390efb5610b0e378fa02c/lib/hooks/grunt/index.js; this is the file that will be in the next release, so it's safe to use now.
