### ISSUE TITLE
User.publishCreate gives maximum stack size exceeded error

### ISSUE THREAD

**Issue by Nishchit14** [balderdashy/sails#3225] opened 2015-09-12 07:47 UTC
I am trying to publishCreate() for socket request but getting this error. 

my ex. is

<pre>
User.create(model) .exec(function createCB(err, usr){
           
            if (err)
                return res.toJson(false, err, 'Error');
           
            if (usr) {
                User.publishCreate({id:usr.id,name : "Nishchit"});
                var s = User.subscribers(usr);
                return res.toJson(true, usr, s);
                //return res.toJson(true, usr, 'User added successfully.');
            }
            else{
                return res.toJson(false, [], 'Error! User can\'t saved.');
            }
    });         
</pre>

Return error

<code>
E:\project\node_modules\sails\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\has-binary-data\index.js:47
        if (obj.hasOwnProperty(key) && _hasBinary(obj[key])) {
                ^
RangeError: Maximum call stack size exceeded
    at Object.hasOwnProperty (native)
    at _hasBinary (E:\project\node_modules\sails\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\has-binary-data\index.js:47:17)
    at _hasBinary (E:\project\node_modules\sails\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\has-binary-data\index.js:47:40)
    at _hasBinary (E:\project\node_modules\sails\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\has-binary-data\index.js:47:40)
    at _hasBinary (E:\project\node_modules\sails\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\has-binary-data\index.js:47:40)
    at _hasBinary (E:\project\node_modules\sails\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\has-binary-data\index.js:47:40)
    at _hasBinary (E:\project\node_modules\sails\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\has-binary-data\index.js:47:40)
    at _hasBinary (E:\project\node_modules\sails\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\has-binary-data\index.js:47:40)
    at _hasBinary (E:\project\node_modules\sails\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\has-binary-data\index.js:47:40)
    at _hasBinary (E:\project\node_modules\sails\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\has-binary-data\index.js:47:40)
    at _hasBinary (E:\project\node_modules\sails\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\has-binary-data\index.js:47:40)
    at _hasBinary (E:\project\node_modules\sails\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\has-binary-data\index.js:47:40)
    at _hasBinary (E:\project\node_modules\sails\node_modules\sails-hook-sockets\node_modules\socket.io\node_modules\has-binary-data\index.js:47:40)

</code>

**Comment by sgress454** [comment] 2015-10-02 17:01
Hi @Nishchit14, it looks like this may have been [fixed on the master branch](https://github.com/balderdashy/sails/pull/2865).  Mind pulling the latest version of Sails into your project and seeing if the issue is resolved?

**Comment by Nishchit14** [comment] 2015-10-05 11:37
Thank you @sgress454 , I am using sails 0.11.0 , And i think this is LTS version of sails.

So do i need to upgrade this version ?

**Comment by sgress454** [comment] 2015-10-16 17:28
Hi @Nishchit14, 0.11.2 is the latest published version of Sails, but the bleeding-edge _unpublished_ version has a fix for this, I think.  To try it out in your project, you can change the "sails" dependency in your project's `package.json` file to:
```
git://github.com/balderdashy/sails.git
```
then remove your node_modules/sails folder and do `npm install`.  Checking this out will help us verify that the new code works and help us get closer to publishing the new version!

**Comment by tjwebb** [comment] 2015-10-25 02:31
> To try it out in your project, you can change the "sails" dependency in your project's package.json file to

FWIW, you can also just set it to `balderdashy/sails` and npm will pull it from Github automatically.

@Nishchit14 let us know if this resolves your issue.

**Comment by Nishchit14** [comment] 2015-10-25 05:07
+1
Thank you.  It works great.

I added this as dependency in package.json

"sails": "git://github.com/balderdashy/sails.git",

**Closed** 2015-10-25 05:56 UTC
