### ISSUE TITLE
Database adapter in connections.js conflicts with local.js when they are defined using different properties

### ISSUE THREAD

**Issue by jurajpetrik** [balderdashy/sails#2761] opened 2015-03-18 21:42 UTC
I want to have a separate db settings for my local development machine and one for production. The way sails accomplishes this by defining local settings in config/local.js and overwriting or **combing** them with the production ones.

So I can define my postgres adapter settings in 2 ways. One way is to use a connection url property, the second way is to user properties for host, user, password etc.

If I define my adapter using the same property in both local.js and connections.js (e.g. by setting the url property in both) it works fine. However if I set it up as below sails try to combine them and I end up with a database connection error.

Maybe this should be an issue in the sails-postgresql repo instead?

    //code in  config/connections.js
     module.exports = {    
        postgresql: {
           adapter: 'sails-postgresql',
           url: "postgres://user:password@localhost/db"  
         } 
     }

     //code in config/local.js
     module.exports = {
       connections: {
         postgresql: {
          adapter: 'sails-postgresql',
          host: 'host',
          user: 'user',
          password: 'password',
          database: 'database'
        }
    }

**Comment by randallmeeker** [comment] 2015-03-19 00:43
I know there is a github issue somewhere that has a reference to this as well? but I can't find it. 

But it Might be related to the following
http://stackoverflow.com/questions/28069677/handling-database-environment-configuration-in-sails-js/28080407#28080407

http://sailsjs.org/#!/documentation/reference/sails.config/sails.config.connections.html?q=multiple-connections-for-an-adapter

**Comment by crh3675** [comment] 2015-03-19 13:43
I don't think this is a bug but a feature by design.  Last I checked, config files are merged which means settings in local.js are for override, not full replacement.  You basically end up with:
```
 module.exports = {
   connections: {
     postgresql: {
      adapter: 'sails-postgresql',
      host: 'host',
      user: 'user',
      password: 'password',
      database: 'database',
      url: "postgres://user:password@localhost/db"  
    }
}
```
Which naturally will create a conflict unless you actually set 
```
url : null 
```
in local.js

**Comment by randallmeeker** [comment] 2015-03-19 14:50
@crh3675 that makes since

**Closed** 2015-04-08 00:42 UTC
Labels: needs documentation, question, waterline

**Comment by maddy2get** [comment] 2016-08-08 01:22
I have config/local.js with connection details for my local machine mongo db, but it always tries to connect with one specified in config/connection.js file (which is remote). Can anyone please provide more documentation on local.js file.

```
// connections.js
module.exports.connections = {
  'mongodb-dev': {
    adapter: 'sails-mongo',
    host: 'test-server.com',
    port: 27017,
    database: 'test-dev'
  },
}
```

```
// local.js
module.exports = {
  connections: {
    'mongodb-dev': {
      adapter: 'sails-mongo',
      host: 'localhost',
      port: 27017,
      database: 'test-local'
    },
  }
}
```

When I sails lift, it tries to connect with database at test-server.com. Any idea what could be happening?
