### ISSUE TITLE
res.jsonx problem

### ISSUE THREAD

**Issue by fernandolguevara** [balderdashy/sails#3440] opened 2015-12-19 18:03 UTC
I am having problems with the error response when trying to save some entity.
Before this commit [b8c3813281a041c0b24db381b046fecfa81a14b7](https://github.com/balderdashy/sails/commit/b8c3813281a041c0b24db381b046fecfa81a14b7) commited by @mikermcneil, the validation errror response looks like
```
{
  "error": "E_VALIDATION",
  "status": 400,
  "summary": "1 attribute is invalid",
  "invalidAttributes": {

    ]
  }
}
```
and now it looks like  
```
{
  "message": "[Error (E_VALIDATION) 1 attribute is invalid] Invalid attributes sent to undefined:\n • abbr\n   • A record with that `...` already exists (`....`).\n",
  "stack": "Error (E_VALIDATION) :: 1 attribute is invalid\nMongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: ...}\n    at Function.MongoError.create (/h......"
}
```

this change will affect all the error handling done by the API consumers

**Comment by crh3675** [comment] 2015-12-19 22:55
Is that environment specific?

**Comment by crh3675** [comment] 2015-12-19 23:03
I don't see this as a problem.  Perhaps the release notes had some info for this update?

**Comment by fernandolguevara** [comment] 2015-12-21 12:06
The Problem Is That We Have to change all the code for handling validations . Sails now returns an entirely different message.

**Comment by fernandolguevara** [comment] 2015-12-22 21:09
this could be an [alternative](http://stackoverflow.com/questions/18391212/is-it-not-possible-to-stringify-an-error-using-json-stringify) to serialize an Error instance

```javascript
Object.defineProperty(Error.prototype, 'toJSON', {
    value: function () {
        var alt = {};

        Object.getOwnPropertyNames(this).forEach(function (key) {
            alt[key] = this[key];
        }, this);

        return alt;
    },
    configurable: true
});
var error = new Error('testing');
error.detail = 'foo bar';

console.log(JSON.stringify(error));
// {"message":"testing","detail":"foo bar"}
```

**Comment by crh3675** [comment] 2015-12-23 00:40
@fernandolguevara  Perhaps this would be a good time to modularize your validation processes.  Not to down-play the annoyance of rewriting code but if you modularize well enough, it might help you later on

**Comment by sgress454** [comment] 2015-12-23 06:24
@fernandolguevara I hesitate to say this since it's been such a long time between releases, but getting breaking changes is the risk you take when you use the unstable branch of a project in your code.  If you want to ensure that the ground doesn't shift underneath you, use the [latest stable release](https://www.npmjs.com/package/sails).  

In this case, you have several options besides rewriting all of your code.  The recommended approach would be to customize the response code in `api/responses` and replace the call to `jsonx` with something which marshals the data in the way you want.  Another option would be to keep the default responses, and instead rewrite the implementation of `jsonx` using a blanket [policy]:

```
// config/policies.js
module.exports.policies = {
   '*': function(req, res, next) {
      res.jsonx = function(data) {
         ...your code here...
      }
      return next();
   }
}
...
```

In any case, closing this out as it's not a bug.

**Closed by sgress454** 2015-12-23 06:24 UTC
